# Generated by Django 5.1.6 on 2025-05-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_test", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=128)),
                ("correo", models.CharField(max_length=128)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
