# Generated by Django 5.1.6 on 2025-03-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_squashed_0004_add_delete_examples"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="state",
            field=models.CharField(
                choices=[
                    ("BR", "BORRADOR"),
                    ("PU", "PUBLICADO"),
                    ("PR", "PRIVADO"),
                ],
                default="BR",
                max_length=2,
            ),
        ),
    ]
