# Generated by Django 5.1.6 on 2025-03-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0007_alter_productmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
